name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install xk6
      run: go install go.k6.io/xk6/cmd/xk6@latest

    - name: Run mqtt broker
      run: docker run -p 1883:1883 -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on --name vernemq -d vernemq/vernemq

    - name: Test from source
      run: xk6 build --with github.com/take-two-t2gp/xk6-mqtt=. && ./k6 run --vus 50 --duration 10s test.js
      
    - name: Test from github
      run: xk6 build --with github.com/take-two-t2gp/xk6-mqtt@latest && ./k6 run --vus 50 --duration 10s test.js
